- name: Ensure Kubic apt key is installed
  apt_key:
    url: "{{ kubic_libcontainers_repo_key_url }}"
    state: present
  become: yes

- name: Ensure Kubic repository is installed
  apt_repository:
    filename: kubic-libcontainers-stable
    repo: deb {{ kubic_libcontainers_repo_url }} /
    state: present
    update_cache: yes
  become: yes
  register: apt_sources

- name: Update packages
  command: apt-get update
  become: yes
  when: apt_sources.changed

- name: Ensure Podman rootless and its dependencies are installed
  apt:
    name: "{{ podman_packages }}"
  become: yes
