- name: Update packages
  command: apt-get update
  become: yes

- name: Ensure Podman rootless and its dependencies are installed
  apt:
    name: "{{ podman_packages }}"
  become: yes

- name: Restart dbus for rootless podman
  shell: systemctl --user restart dbus
