- name: Ensure buster-backports apt key is installed
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
    state: present
  become: yes
  with_items:
    - 04EE7237B7D453EC
    - 648ACFD622F3D138

- name: Ensure buster-backports repository is installed
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    state: present
  become: yes

- name: Ensure libseccomp2 from buster-backports is installed
  apt:
    name: libseccomp2=2.4.4-1~bpo10+1
    state: present
  become: yes

- name: Ensure Kubic apt key is installed
  apt_key:
    url: "{{ kubic_libcontainers_repo_key_url }}"
    state: present
  become: yes

- name: Ensure Kubic repository is installed
  apt_repository:
    filename: kubic-libcontainers-stable
    repo: deb {{ kubic_libcontainers_repo_url }} /
    state: present
    update_cache: yes
  become: yes
  register: apt_sources

- name: Update packages
  command: apt-get update
  become: yes
  when: apt_sources.changed

- name: Ensure Podman rootless and its dependencies are installed
  apt:
    name: "{{ podman_packages }}"
  become: yes

- name: Restart dbus for rootless podman
  shell: systemctl --user restart dbus
