- include: install-on-raspbian.yml
  when: ansible_distribution == 'Debian'

- include: install-on-fedora.yml
  when: ansible_distribution == 'Fedora'

- include: setup-podman-container.yml
  loop: "{{ podman_containers }}"
  loop_control:
    loop_var: container
